### ISSUE TITLE
Can't take samples

### ISSUE THREAD

**Issue by elkatronas** [Royal-Modding/FS19_PrecisionFarmingAddon#12]
Hello, I don't know if that's an issue or not, but when my field data goes old (Outdated data), I can't take new samples from whole field (I can't hire geologist to do it).

I hope I explained it good.

**Comment by Cassy-Blair** [comment]
> 
> 
> Hello, I don't know if that's an issue or not, but when my field data goes old (Outdated data), I can't take new samples from whole field (I can't hire geologist to do it).
> 
> I hope I explained it good.

Have a look [here](https://github.com/Royal-Modding/FS19_PrecisionFarmingAddon/issues/9), there you will find the solution

**Comment by elkatronas** [comment]
![image](https://user-images.githubusercontent.com/79064028/125902857-fe22c0b4-ba94-4352-8380-7a109cac1a8b.png)
It still doesn't work..

**Comment by elkatronas** [comment]
![fsScreen_2021_07_16_09_32_39](https://user-images.githubusercontent.com/79064028/125902917-1102e766-7503-4588-b978-d146566719f3.png)
It still doesn't work

**Comment by Cassy-Blair** [comment]
> 
> 
> ![fsScreen_2021_07_16_09_32_39](https://user-images.githubusercontent.com/79064028/125902917-1102e766-7503-4588-b978-d146566719f3.png)
> It still doesn't work

Have you edited **line 29** in **PrecisionFarmingAddon.lua** with notepad ++ and entered the following **_requiredVersion = "1.0.2.1"?_**

**Comment by elkatronas** [comment]
> > ![fsScreen_2021_07_16_09_32_39](https://user-images.githubusercontent.com/79064028/125902917-1102e766-7503-4588-b978-d146566719f3.png)
> > It still doesn't work
> 
> Have you edited **line 29** in **PrecisionFarmingAddon.lua** with notepad ++ and entered the following **_requiredVersion = "1.0.2.1"?_**

Now it works. All I did was download fresh from modhub and edit line 29, now it works like a charm!
