### ISSUE TITLE
Can't see button Request analysis

### ISSUE THREAD

**Issue by elkatronas** [Royal-Modding/FS19_PrecisionFarmingAddon#4]
Request analysis button not appearing
![fsScreen_2021_03_01_12_51_55](https://user-images.githubusercontent.com/79064028/109487469-ed4a1f00-7a8c-11eb-8f0b-d6e131e5cc6d.png)

**Comment by TyKonKet** [comment]
That's an issue with the latest version of Precision Farming Addon by GIANTS, we already fixed it and the updated version should be released today on ModHub.

**Comment by elkatronas** [comment]
> That's an issue with the latest version of Precision Farming Addon by GIANTS, we already fixed it and the updated version should be released today on ModHub.

Thank god, I was worried. First time trying precision and your mod would be very useful because my fields are huge. Thanks for the work!

**Comment by elkatronas** [comment]
Update just got out on ModHub, it works perfect now!

**Comment by TyKonKet** [comment]
> Update just got out on ModHub, it works perfect now!

Nice!

**Comment by yitzh4k** [comment]
I am also having the same issue, with the latest version of both mods.

**Comment by TyKonKet** [comment]
@yitzh4k that's very strange, we aren't able to notice any issue with latest versions of them both.
Are you sure you have latest versions?
Precision Farming DLC = 1.0.2.0
and
Precision Farming Addon = 1.1.0.0
