### ISSUE TITLE
Feld scannen nicht möglich

### ISSUE THREAD

**Issue by Andy2612** [Royal-Modding/FS19_PrecisionFarmingAddon#9]
Hallo, nach dem neuen Update von Giants beim Precision Farming DLC ist das Scannen der Felder durch den Geologen nicht mehr möglich.

**Comment by regs1980** [comment]
Das Addon muss an die Precision Farming DLC Version 1.0.2.1 angepasst werden, PrecisionFarmingAddon.lua mit einem Text Editor öffnen und 

<img width="555" alt="2021-07-04 23_29_11-PrecisionFarmingAddon - Editor" src="https://user-images.githubusercontent.com/13314443/124400026-c1cb8f80-dd1f-11eb-8bac-f603e100ed33.png">

das rot markierte von 1.0.2.0 auf 1.0.2.1 ändern dann funktioniert das Addon wieder.

**Comment by Andy2612** [comment]
Danke, werde ich ändern. wahrscheinlich für die Zukunft dann auch immer 
anpassen denke ich.



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: regs1980
Betreff: Re: [Royal-Modding/FS19_PrecisionFarmingAddon] Feld scannen nicht 
möglich (#9)
Datum: 04. Juli 2021, 23:31
An: Royal-Modding/FS19_PrecisionFarmingAddon
Cc: Andy2612, Author



Das Addon muss an die Precision Farming DLC Version 1.0.2.1 angepasst 
werden, PrecisionFarmingAddon.lua mit einem Text Editor öffnen und

[2021-07-04 23_29_11-PrecisionFarmingAddon - Editor]
<https://user-images.githubusercontent.com/13314443/124400026-c1cb8f80-dd1f-11eb-8bac-f603e100ed33.png>

das rot markierte von 1.0.2.0 auf 1.0.2.1 ändern dann funktioniert das 
Addon wieder.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Royal-Modding/FS19_PrecisionFarmingAddon/issues/9#issuecomment-873666197> 
, or unsubscribe

**Comment by EradicationGod** [comment]
Hi there, I have updated Precision Farming DLC to 1.0.3.1, it adds a fix and two filltypes.
It all works fine with no errors, but for some reason I can't get the PF addon to link to the base mod.
I applied the mentioned fix above, only with the correct version number 1.0.3.1 in the .lua but to no avail.
[FS19_precisionFarming.zip](https://github.com/Royal-Modding/FS19_PrecisionFarmingAddon/files/8047766/FS19_precisionFarming.zip)
[FS19_PrecisionFarmingAddon.zip](https://github.com/Royal-Modding/FS19_PrecisionFarmingAddon/files/8047768/FS19_PrecisionFarmingAddon.zip)


Can you plz help me with this?
